name: Release
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build for release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - name: Test
        run: go test -v ./...
      - name: Send Release Alert
        working-directory: ./sample
        run: go run github.go --release
        env:
          APIALERTS_API_KEY: ${{ secrets.APIALERTS_API_KEY }}